add_newline = false

[line_break]
disabled = true

[container]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[golang]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[lua]
disabled = true

[cmd_duration]
disabled = true

